name: Build Arch Linux Docker Image
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - archlinux
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: build docker image and push to docker hub
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "archlinux"
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: fr4nk1in/archlinux:latest
